version: "3.8"

services:
  web:
    image: nginx
    working_dir: /dfyqst
    volumes:
      - ./dist:/dfyqst/dist
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 23000:80
    restart: always
